// 2008/7/3 Scripted by K-Factory@migiwa
// 2009/1/27 Modified by K-Factory@migiwa
// 2014/6/29 Modified by nkeronkow
// 2018/11/26 Added to relick's github, changes tracked there
// github.com/relick/touhou-song-sorter

// *****************************************************************************
"use strict";
const str_CenterT = 'Tie!';
const str_CenterB = 'Undo last choice';

const str_ImgPath = 'images/';
const str_YouPath = 'https://www.youtube.com/embed/';
const str_YouLink = 'https://www.youtube.com/watch?v=';

// Up to which position should images be shown for?
var int_ResultRank = 3;

// Maximum number of result rows before being broken off into another table.
var maxRows = 42;

// Letty waz here
const deepFreeze = obj => {
	Object.keys(obj).forEach(prop => {
		if (typeof obj[prop] === 'object') deepFreeze(obj[prop]);
	}); return Object.freeze(obj);
};

// * Game and album titles
// name: used in the selection table before starting a sort
// image: 180x180px CD artwork
// shortName: used during the sort
// abbrev: abbreviated form (used in the final result table)
const TITLE = deepFreeze({
	ORIGIN: { name: "CHUNITHM", image: "chunithm.png", shortName: "CHUNITHM", abbrev: "CHUNITHM" },
	ORIGIN_PLUS: { name: "CHUNITHM PLUS", image: "plus.png", shortName: "PLUS", abbrev: "CHUNITHM+" },
	AIR: { name: "CHUNITHM AIR", image: "air.png", shortName: "AIR", abbrev: "AIR" },
	AIR_PLUS: { name: "CHUNITHM AIR PLUS", image: "airplus.png", shortName: "AIR PLUS", abbrev: "AIR+" },
	STAR: { name: "CHUNITHM STAR", image: "star.png", shortName: "STAR", abbrev: "STAR" },
	STAR_PLUS: { name: "CHUNITHM STAR PLUS", image: "starplus.png", shortName: "STAR PLUS", abbrev: "STAR+" },
	AMAZON: { name: "CHUNITHM AMAZON", image: "amazon.png", shortName: "AMAZON", abbrev: "AMAZON" },
	AMAZON_PLUS: { name: "CHUNITHM AMAZON PLUS", image: "amazonplus.png", shortName: "AMAZON PLUS", abbrev: "AMAZON+" },
	CRYSTAL: { name: "CHUNITHM CRYSTAL", image: "crystal.png", shortName: "CRYSTAL", abbrev: "CRYSTAL" },
	CRYSTAL_PLUS: { name: "CHUNITHM CRYSTAL PLUS", image: "crystalplus.png", shortName: "CRYSTAL PLUS", abbrev: "CRYSTAL+" },
	PARADISE: { name: "CHUNITHM PARADISE", image: "paradise.png", shortName: "PARADISE", abbrev: "PARADISE" },
	PARADISE_LOST: { name: "CHUNITHM PARADISE LOST", image: "paradiselost.png", shortName: "PARADISE LOST", abbrev: "PARADISE×" },
	NEW: { name: "CHUNITHM NEW", image: "new.png", shortName: "NEW", abbrev: "NEW" },
	NEW_PLUS: { name: "CHUNITHM NEW PLUS", image: "newplus.png", shortName: "NEW PLUS", abbrev: "NEW+" },
	SUN: { name: "CHUNITHM SUN", image: "sun.png", shortName: "SUN", abbrev: "SUN" },
	SUN_PLUS: { name: "CHUNITHM SUN PLUS", image: "sunplus.png", shortName: "SUN PLUS", abbrev: "SUN+" },
	LUMINOUS: { name: "CHUNITHM LUMINOUS", image: "luminous.png", shortName: "LUMINOUS", abbrev: "LUMINOUS" },
	LUMINOUS_PLUS: { name: "CHUNITHM LUMINOUS PLUS", image: "luminousplus.png", shortName: "LUMINOUS PLUS", abbrev: "LUMINOUS+" },
	VERSE: { name: "CHUNITHM VERSE", image: "verse.png", shortName: "VERSE", abbrev: "VERSE" },
    X_VERSE: { name: "CHUNITHM X-VERSE", image: "x-verse.png", shortName: "X-VERSE", abbrev: "X-VERSE" },
    X_VERSE_X: { name: "CHUNITHM X-VERSE-X", image: "x-verse.png", shortName: "X-VERSE-X", abbrev: "X-VERSE-X" },
});

// Not included in main filters, but used for song data display
const EXTRA_TITLES = deepFreeze({
	
});

const getTitleData = function (songTitleDataObj) {
	// We'll have to handle individual song overrides either way (mostly going to be coming from old saved data)

	const titleData = TITLE[songTitleDataObj.title];

	if (!songTitleDataObj.extra) {
		return {
			name: titleData.name,
			image: songTitleDataObj.image || titleData.image,
			shortName: songTitleDataObj.shortName || titleData.shortName,
			abbrev: songTitleDataObj.abbrev || titleData.abbrev,
		};
	}

	// Also handle extra overrides
	const extraTitleData = EXTRA_TITLES[songTitleDataObj.extra];
	return {
		name: titleData.name,
		image: songTitleDataObj.image || extraTitleData.image || titleData.image,
		shortName: songTitleDataObj.shortName || extraTitleData.shortName || titleData.shortName,
		abbrev: songTitleDataObj.abbrev || extraTitleData.abbrev || titleData.abbrev,
	};
}

const CATEGORY = deepFreeze({
	CHUNITHM: {
		name: "CHUNITHM",
		titles: [
			"ORIGIN",
			"ORIGIN_PLUS",
			"AIR",
			"AIR_PLUS",
			"STAR",
			"STAR_PLUS",
			"AMAZON",
			"AMAZON_PLUS",
			"CRYSTAL",
			"CRYSTAL_PLUS",
			"PARADISE",
			"PARADISE_LOST",
			"NEW",
			"NEW_PLUS",
			"SUN",
			"SUN_PLUS",
			"LUMINOUS",
			"LUMINOUS_PLUS",
			"VERSE",
			"X-VERSE",
			"X-VERSE-X",
		]
	}
});

// Number of columns in the selection list.
var int_Colspan = 3;

// * Music information
// [Index: Meaning]
// 0: Track name
const TRACK_NAME = 0;
// 1: Set of titles that this track appears in
const TRACK_TITLES = 1;
// 2: Object specifying the title to draw data from, and any overrides
const TRACK_TITLE_DATA = 2;
// 3: Youtube video ID
const TRACK_YOUTUBE_ID = 3;
// 4: Description of track
const TRACK_DESCRIPTION = 4;
// 5: If the *exact* same track appears in a later game then it should use [1] to specify rather than setting as arrangement.
const TRACK_IS_ARRANGEMENT = 5;
	const ORIGINAL_TRACK = 0;
	const ARRANGED_TRACK = 1;
// 6: Track type, Album tracks should all be marked as OTHER_THEME.
const TRACK_TYPE = 6;
	const STAGE_THEME = 0;
	const BOSS_THEME = 1;
	const STAGE_AND_BOSS_THEME = 2;
	const OTHER_THEME = 3;

// Old song data format, for transitioning old save data
// 2: Image filename
const LEGACY_TRACK_IMAGE = 2;
// 4: Title (game/album) name
const LEGACY_TRACK_TITLE_NAME = 4;
// 5: Title (game/album) abbreviation
const LEGACY_TRACK_TITLE_ABBREV = 5;

// Find: https://(?:music.|www.)?youtube.com/watch\?v=([0-9a-zA-Z-_]{11})&si=[0-9a-z-A-Z-_]+
// Replace: $1
var ary_SongData = [
	["My First Phone", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "hy3YNY9K6u4", "cubesato", ORIGINAL_TRACK, OTHER_THEME],
	["Cyberozar", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "kaVV0MqrJ6E", "削除", ORIGINAL_TRACK, OTHER_THEME],
	["Teriqma", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "U4mhbtQC0sE", "owl＊tree", ORIGINAL_TRACK, OTHER_THEME],
	["Invitation", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "EJdMNzHKo9w", "れるりり feat.ろん", ORIGINAL_TRACK, OTHER_THEME],
	["GOLDEN RULE", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "FLjVYngoSfU", "Morrigan", ORIGINAL_TRACK, OTHER_THEME],
	["名も無い鳥", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "fcYObdtO96Y", "六弦アリス", ORIGINAL_TRACK, OTHER_THEME],
	["Gate of Fate", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "xMHtOX1SdP4", "Godspeed", ORIGINAL_TRACK, OTHER_THEME],
	["今ぞ♡崇め奉れ☆オマエらよ！！～姫の秘メタル渇望～", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "_mqNZMi-WNc", "あべにゅうぷろじぇくと feat.佐倉 紗織　produced by ave;new", ORIGINAL_TRACK, OTHER_THEME],
	["Anemone", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "gZgNzHX8yUo", "ESTi", ORIGINAL_TRACK, OTHER_THEME],
	["明るい未来", new Set([TITLE.AIR]), { title: "AIR" }, "L9eBVk_wFCY", "豚乙女", ORIGINAL_TRACK, OTHER_THEME],
	["昵懇レファレンス", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "IQOxt2Qz76g", "halyosy", ORIGINAL_TRACK, OTHER_THEME],
	["乗り切れ受験ウォーズ", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "GsSq-ptx4Jg", "solfa feat.茶太", ORIGINAL_TRACK, OTHER_THEME],
	["The wheel to the right", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "E4LyGfc8AaY", "Sampling Masters MEGA", ORIGINAL_TRACK, OTHER_THEME],
	["STAR", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "NKZh2_Wq70Y", "SEXY-SYNTHESIZER", ORIGINAL_TRACK, OTHER_THEME],
	["Infantoon Fantasy", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "QuurKzcfki8", "t+pazolite", ORIGINAL_TRACK, OTHER_THEME],
	["Genesis", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "sw1WtD6NGmQ", "Morrigan feat.Lily", ORIGINAL_TRACK, OTHER_THEME],
	["MUSIC PЯAYER", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "QzSTMPBI3nw", "A-One", ORIGINAL_TRACK, OTHER_THEME],
	["リリーシア", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "uS_AB6Fd3mY", "TaNaBaTa", ORIGINAL_TRACK, OTHER_THEME],
	["Counselor", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "vGlkCuWO23w", "DECO*27 feat.echo", ORIGINAL_TRACK, OTHER_THEME],
	["luna blu", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "zka59yD47DE", "WASi303", ORIGINAL_TRACK, OTHER_THEME],
	["ケモノガル", new Set([TITLE.AIR]), { title: "AIR" }, "pr_-1oGd8Gw", "ゼッケン屋", ORIGINAL_TRACK, OTHER_THEME],
	["ＧＯ！ＧＯ！ラブリズム♥", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "mo_PcRIGyCI", "片霧烈火オンザみんマンション", ORIGINAL_TRACK, OTHER_THEME],
	["Grab your sword", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "v7BEt0ZjMTk", "古代 祐三", ORIGINAL_TRACK, OTHER_THEME],
	["Memories of Sun and Moon", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "8stB5ViYkII", "Aiko Oi", ORIGINAL_TRACK, OTHER_THEME],
	["L'épisode", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "NQ2ZYu_uSIo", "Osamu Kubota", ORIGINAL_TRACK, OTHER_THEME],
	["砂漠のハンティングガール♡", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "71X0aQoWAh8", "海田 明里", ORIGINAL_TRACK, OTHER_THEME],
	["After the rain", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "7Q7jXQ8KSGs", "霜月はるか", ORIGINAL_TRACK, OTHER_THEME],
	["Tango Rouge", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "eJcFWpDgCtg", "Yoko Shimomura", ORIGINAL_TRACK, OTHER_THEME],
	["Tuning Rangers", new Set([TITLE.AIR]), { title: "AIR" }, "fLgutbajkqc", "COOL&CREATE", ORIGINAL_TRACK, OTHER_THEME],
	["エンドマークに希望と涙を添えて", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "tLlw4PPx5xc", "cosMo＠暴走P", ORIGINAL_TRACK, OTHER_THEME],
	["とーきょー全域★アキハバラ？", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "6ZX_QfWjHps", "MOSAIC.WAV", ORIGINAL_TRACK, OTHER_THEME],
	["overcome", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "R0XAmL7fPG8", "景山 将太", ORIGINAL_TRACK, OTHER_THEME],
	["宛城、炎上！！", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "z00jVQS3eU0", "Cranky feat.おもしろ三国志", ORIGINAL_TRACK, OTHER_THEME],
	["We Gonna Journey", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "w3O6ao-N1FI", "Queen P.A.L.", ORIGINAL_TRACK, OTHER_THEME],
	["The ether", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "0UVeYJJJ9Ys", "浜渦 正志", ORIGINAL_TRACK, OTHER_THEME],
	["Guilty", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "Cgm02s7XZQo", "MintJam", ORIGINAL_TRACK, OTHER_THEME],
	["閃鋼のブリューナク", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "LFqEZDTJGaY", "sasakure.UK", ORIGINAL_TRACK, OTHER_THEME],
	["夕暮れワンルーム", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "NSDg71nyp9E", "40mP feat.シャノ", ORIGINAL_TRACK, OTHER_THEME],
	["こころここから", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "_4k5TqXpumM", "ふわりP", ORIGINAL_TRACK, OTHER_THEME],
	["Theme of SeelischTact", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "NlApALkvGuQ", "植松 伸夫", ORIGINAL_TRACK, OTHER_THEME],
	["Alma", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "FGMJ4o-kKBg", "光田 康典", ORIGINAL_TRACK, OTHER_THEME],
	["Gustav Battle", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "CrbPVyoEBz8", "伊藤 賢治", ORIGINAL_TRACK, OTHER_THEME],
	["幾四音-Ixion-", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "-L02AdGuc60", "M.S.S Project", ORIGINAL_TRACK, OTHER_THEME],
	["stella=steLLa", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "nih4vahW42g", "marasy", ORIGINAL_TRACK, OTHER_THEME],
	["怒槌", new Set([TITLE.ORIGIN]), { title: "ORIGIN" }, "3vQ3o8o0TeU", "光吉猛修", ORIGINAL_TRACK, OTHER_THEME],
	["Contrapasso -inferno-", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "5gB_KBgxW5A", "t+pazolite", ORIGINAL_TRACK, OTHER_THEME],
	["GEMINI -C-", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "RamHpo7LatE", "Tatsh", ORIGINAL_TRACK, OTHER_THEME],
	["SNIPE WHOLE", new Set([TITLE.ORIGIN_PLUS]), { title: "ORIGIN_PLUS" }, "VNPGN9fIjtA", "Masayoshi Minoshima feat.Mei Ayakura", ORIGINAL_TRACK, OTHER_THEME],
	["サウンドプレイヤー", new Set([TITLE.AIR]), { title: "AIR" }, "99bvBC_s1Cw", "tilt-six feat.バル", ORIGINAL_TRACK, OTHER_THEME],
	["玩具狂奏曲 -終焉-", new Set([TITLE.AIR]), { title: "AIR" }, "RwFw9-ze6K4", "きくお", ORIGINAL_TRACK, OTHER_THEME],
	["紅華刑", new Set([TITLE.AIR]), { title: "AIR" }, "JjOw3zFqO3Y", "-45", ORIGINAL_TRACK, OTHER_THEME],
	["Hyperion", new Set([TITLE.AIR]), { title: "AIR" }, "e_fnHwk_GHM", "Maozon", ORIGINAL_TRACK, OTHER_THEME],
	["Devastating Blaster", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "Dj5WUOTkBGM", "INNOCENT NOIZE", ORIGINAL_TRACK, OTHER_THEME],
	["Schrecklicher Aufstand", new Set([TITLE.AIR]), { title: "AIR" }, "wmoskXIzwoM", "Katzeohr & Spiegel", ORIGINAL_TRACK, OTHER_THEME],
	["ドライヴ・オン・ザ・レインボー", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "q5DrUllycGM", "並木晃一", ORIGINAL_TRACK, OTHER_THEME],
	["Philosopher", new Set([TITLE.AIR]), { title: "AIR" }, "-O_VLc1Gr1I", "少女病", ORIGINAL_TRACK, OTHER_THEME],
	["Warcry", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "dmCSESaEOOU", "YATAGARASU", ORIGINAL_TRACK, OTHER_THEME],
	["その群青が愛しかったようだった", new Set([TITLE.AIR]), { title: "AIR" }, "pbVNuF3SjFU", "n-buna feat.ヤギヌマカナ", ORIGINAL_TRACK, OTHER_THEME],
	["札付きのワル　～マイケルのうた～", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "4zvplOWtFJE", "ひーちゃんとあーちゃんとたーちゃん", ORIGINAL_TRACK, OTHER_THEME],
	["BOKUTO", new Set([TITLE.AIR]), { title: "AIR" }, "KrxeIpkLoSY", "じーざすP feat.kradness", ORIGINAL_TRACK, OTHER_THEME],
	["TiamaT:F minor", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "ynwbngCuJJ4", "Team Grimoire", ORIGINAL_TRACK, OTHER_THEME],
	["Oshama Scramble! (Cranky Remix)", new Set([TITLE.AIR]), { title: "AIR" }, "R6o7IbwmIBo", "Cranky", ORIGINAL_TRACK, OTHER_THEME],
	["D.E.A.D.L.Y.", new Set([TITLE.AIR]), { title: "AIR" }, "ngrhvAKrQLc", "さつき が てんこもり feat.YURiCa/花たん", ORIGINAL_TRACK, OTHER_THEME],
	["ロボットプラネットユートピア", new Set([TITLE.AIR]), { title: "AIR" }, "ylH6VpJAoME", "lumo", ORIGINAL_TRACK, OTHER_THEME],
	["Tidal Wave", new Set([TITLE.AIR]), { title: "AIR" }, "ZvFDjp6gsLY", "D-Cee", ORIGINAL_TRACK, OTHER_THEME],
	["ゲシュタルト！テスト期間！！", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "35Pxpz8j1_U", "solfa feat.茶太", ORIGINAL_TRACK, OTHER_THEME],
	["心象蜃気楼", new Set([TITLE.AIR]), { title: "AIR" }, "mth-c66_8XE", "Orangestar", ORIGINAL_TRACK, OTHER_THEME],
	["願い星", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "vBPJoP4TCVU", "霜月はるか", ORIGINAL_TRACK, OTHER_THEME],
	["後夜祭", new Set([TITLE.AIR]), { title: "AIR" }, "F45D8y64k9Y", "田口囁一／感傷ベクトル", ORIGINAL_TRACK, OTHER_THEME],
	["First Twinkle", new Set([TITLE.AIR]), { title: "AIR" }, "PoJfDEXasuo", "折戸伸治 feat.北沢綾香", ORIGINAL_TRACK, OTHER_THEME],
	["ウソラセラ", new Set([TITLE.AIR]), { title: "AIR" }, "iKGxb6jNmJA", "ピノキオピー", ORIGINAL_TRACK, OTHER_THEME],
	["響", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "z4nqZOZwnVM", "志方あきこ", ORIGINAL_TRACK, OTHER_THEME],
	["Paqqin", new Set([TITLE.AIR]), { title: "AIR" }, "U7V9YzltksE", "owl＊tree", ORIGINAL_TRACK, OTHER_THEME],
	["覚醒楽奏メタフィクション", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "OEQdACDp4MU", "マチゲリータ", ORIGINAL_TRACK, OTHER_THEME],
	["Supersonic Generation", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "7MsIK-TGZic", "Massive New Krew", ORIGINAL_TRACK, OTHER_THEME],
	["RevolutionGame", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "RkcjGVV2XBc", "れるりり feat.ろん", ORIGINAL_TRACK, OTHER_THEME],
	["おまかせ！！トラブルメイ娘☆とれびちゃん", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "6mY68iuyk20", "かたほとり feat.桃箱", ORIGINAL_TRACK, OTHER_THEME],
	["オススメ☆♂♀☆でぃすとぴあ", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "PJ4Dy1_Xk2M", "ULTRA-PRISM", ORIGINAL_TRACK, OTHER_THEME],
	["最愛テトラグラマトン", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "Daifx0RR5w0", "片霧烈火", ORIGINAL_TRACK, OTHER_THEME],
	["混沌を越えし我らが神聖なる調律主を讃えよ", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "7xVKmkN8fHM", "穴山大輔", ORIGINAL_TRACK, OTHER_THEME],
	["We Gonna Party -Feline Groove Mix-", new Set([TITLE.AIR_PLUS]), { title: "AIR_PLUS" }, "G3Bi7NGLhwI", "Morrigan feat.Lily", ORIGINAL_TRACK, OTHER_THEME],
	["光線チューニング", new Set([TITLE.STAR]), { title: "STAR" }, "sUIzvcmTz-0", "ナユタン星人", ORIGINAL_TRACK, OTHER_THEME],
	["立川浄穢捕物帳", new Set([TITLE.STAR]), { title: "STAR" }, "GJXZd4UXEb8", "青島探偵事務所器楽捜査部B担", ORIGINAL_TRACK, OTHER_THEME],
	["眠れぬ夜君を想フ", new Set([TITLE.STAR]), { title: "STAR" }, "YGh0i_yTru0", "baker", ORIGINAL_TRACK, OTHER_THEME],
	["JIGOKU STATION CENTRAL GATE", new Set([TITLE.STAR]), { title: "STAR" }, "qMK-1tGQoMg", "鬱P feat.000", ORIGINAL_TRACK, OTHER_THEME],
	["PinqPiq", new Set([TITLE.STAR]), { title: "STAR" }, "Yx0GCCzoOzw", "owl＊tree feat.awao＊tree", ORIGINAL_TRACK, OTHER_THEME],
	["トリスメギストス", new Set([TITLE.STAR]), { title: "STAR" }, "Rk9A_W6_5ag", "bermei.inazawa", ORIGINAL_TRACK, OTHER_THEME],
	["WE GOTTA SOUL", new Set([TITLE.STAR]), { title: "STAR" }, "-wdEWQEgn1g", "魂音泉", ORIGINAL_TRACK, OTHER_THEME],
	["哀しみ集め", new Set([TITLE.STAR]), { title: "STAR" }, "huchprcskSA", "幽閉サテライト", ORIGINAL_TRACK, OTHER_THEME],
	["キラメケ→Shoot it Now!", new Set([TITLE.STAR]), { title: "STAR" }, "fJ5G5lLRoYE", "t+pazolite feat.ななひら", ORIGINAL_TRACK, OTHER_THEME],
	["Kattobi KEIKYU Rider", new Set([TITLE.STAR]), { title: "STAR" }, "_-Tsx9csjQY", "Sampling Masters MEGA", ORIGINAL_TRACK, OTHER_THEME],
	["Glorious Crown (tpz over-Over-OVERCUTE REMIX)", new Set([TITLE.STAR]), { title: "STAR" }, "GdcEjumvW_w", "t+pazolite", ORIGINAL_TRACK, OTHER_THEME],
	["Wake up Dreamer", new Set([TITLE.STAR]), { title: "STAR" }, "OvCQy-KlQNM", "Junk", ORIGINAL_TRACK, OTHER_THEME],
	["World Vanquisher", new Set([TITLE.STAR]), { title: "STAR" }, "MXzU7AvdXIM", "void (Mournfinale)", ORIGINAL_TRACK, OTHER_THEME],
	["macrocosmos", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "SuNDzIlBd0s", "LeaF", ORIGINAL_TRACK, OTHER_THEME],
	["Iudicium", new Set([TITLE.STAR]), { title: "STAR" }, "EqbMdkdirLo", "Powerless feat.kakichoco", ORIGINAL_TRACK, OTHER_THEME],
	["Twice up Scenery", new Set([TITLE.STAR]), { title: "STAR" }, "0TAfvFrbqng", "q/stol", ORIGINAL_TRACK, OTHER_THEME],
	["Xevel", new Set([TITLE.STAR]), { title: "STAR" }, "WpdRLdigmnE", "Tatsh", ORIGINAL_TRACK, OTHER_THEME],
	["La Baguette Magique", new Set([TITLE.STAR]), { title: "STAR" }, "hqqS-A2DyW0", "OSTER project feat.ジェム", ORIGINAL_TRACK, OTHER_THEME],
	["bubble attack", new Set([TITLE.STAR]), { title: "STAR" }, "ioJHFQRCZpU", "HALFBY", ORIGINAL_TRACK, OTHER_THEME],
	["The Darkness of Valhalla", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "vaF5HjfT0_M", "うたたP", ORIGINAL_TRACK, OTHER_THEME],
	["時の冒険者", new Set([TITLE.STAR]), { title: "STAR" }, "vcfofN0rGSI", "40mP feat.シャノ", ORIGINAL_TRACK, OTHER_THEME],
	["Rendezvous", new Set([TITLE.STAR]), { title: "STAR" }, "3hWHWwg3w2M", "Crusher-P", ORIGINAL_TRACK, OTHER_THEME],
	["EXECUTOR", new Set([TITLE.STAR]), { title: "STAR" }, "rfKrU0ZhJE0", "doriko feat.VALSHE", ORIGINAL_TRACK, OTHER_THEME],
	["BlazinG AIR", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "46OZNraGKhs", "kanone", ORIGINAL_TRACK, OTHER_THEME],
	["Sparking Revolver", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "n7AqRLbeaI0", "xi", ORIGINAL_TRACK, OTHER_THEME],
	["Gate of Doom", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "n5vJZDyDPKY", "Masahiro “Godspeed” Aoki", ORIGINAL_TRACK, OTHER_THEME],
	["otorii INNOVATED -[i]3-", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "BX7Mgsu2L5o", "NAOKI underground", ORIGINAL_TRACK, OTHER_THEME],
	["popcorn", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "hc0BW0i0-o8", "happy machine", ORIGINAL_TRACK, OTHER_THEME],
	["Pastel Party", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "DIOgTst7mbo", "Tomggg", ORIGINAL_TRACK, OTHER_THEME],
	["はちみつアドベンチャー", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "-yZlaC9dRe8", "Yunomi feat.nicamoq", ORIGINAL_TRACK, OTHER_THEME],
	["CHOCOLATE BOMB!!!!", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "2MXOQSSjFQY", "YUC'e", ORIGINAL_TRACK, OTHER_THEME],
	["Twilight", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "ct6l23xQsUU", "Pa's Lam System", ORIGINAL_TRACK, OTHER_THEME],
	["Sentimental Snow", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "TC4bM0QeUTQ", "霜月はるか", ORIGINAL_TRACK, OTHER_THEME],
	["サンシャインサマー☆夏期講習", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "ulbQmrl727I", "solfa feat.茶太", ORIGINAL_TRACK, OTHER_THEME],
	["NYAN-NYA, More! ラブシャイン、Chu♥", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "qU9nLY-ZKGc", "片霧烈火オンザみんマンション", ORIGINAL_TRACK, OTHER_THEME],
	["Dual Fractal", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "PsqSEp_0L5E", "M2U", ORIGINAL_TRACK, OTHER_THEME],
	["Drivessover", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "1N2BmY6pl4g", "Taishi", ORIGINAL_TRACK, OTHER_THEME],
	["Surveiller et punir", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "3W8SQLkQGJY", "cybermiso", ORIGINAL_TRACK, OTHER_THEME],
	["業 -善なる神とこの世の悪について-", new Set([TITLE.STAR_PLUS]), { title: "STAR_PLUS" }, "G4Kf0bUAm4o", "光吉猛修 VS 穴山大輔", ORIGINAL_TRACK, OTHER_THEME],
	["朝焼けプラットホーム", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "g0r6i7AZEfw", "40mP feat.シャノ", ORIGINAL_TRACK, OTHER_THEME],
	["PAST", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "hP3R0WVO7F0", "164 feat.ウォルピスカーター", ORIGINAL_TRACK, OTHER_THEME],
	["Blessed", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "DdhIbqglrF8", "Palme", ORIGINAL_TRACK, OTHER_THEME],
	["FRIDAY FRIDAY", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "AaRWxbXKBns", "emon(Tes.) feat.松平なな", ORIGINAL_TRACK, OTHER_THEME],
	["足立オウフwwww", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "5ryFjaA_YdQ", "笑う角を曲がる", ORIGINAL_TRACK, OTHER_THEME],
	["Seagull", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "YW_BpmXLoIw", "Snail's House", ORIGINAL_TRACK, OTHER_THEME],
	["Blaster Heaven", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "_SbatXklgM0", "カヒーナムジカ", ORIGINAL_TRACK, OTHER_THEME],
	["ハートアタック", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "R5-XTQgkxDE", "Omoi feat.+α/あるふぁきゅん。", ORIGINAL_TRACK, OTHER_THEME],
	["Summer is over", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "nX1ZXzOpO1g", "TORIENA", ORIGINAL_TRACK, OTHER_THEME],
	["folern", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "54Mjq-QgT-Y", "ぬゆり", ORIGINAL_TRACK, OTHER_THEME],
	["2DVenture", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "dGaEMytQ4iI", "dawn-system", ORIGINAL_TRACK, OTHER_THEME],
	["ぜったい！昇天★鎮魂歌♂", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "IcxXy8KP6as", "NirNo", ORIGINAL_TRACK, OTHER_THEME],
	["夕焼けのRed Parade", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "gtnaRdVV0go", "technoplanet", ORIGINAL_TRACK, OTHER_THEME],
	["StufeStern", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "esu8ZL2xVNo", "Feryquitous", ORIGINAL_TRACK, OTHER_THEME],
	["スピカの天秤", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "hoObeIMkAFU", "Acotto", ORIGINAL_TRACK, OTHER_THEME],
	["涙色メモリア", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "QBEPmZBiX-4", "キノシタ feat.YURiCa/花たん", ORIGINAL_TRACK, OTHER_THEME],
	["Magic", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "8ATLDBGndkw", "niki feat.noire", ORIGINAL_TRACK, OTHER_THEME],
	["男装女形表裏一体発狂小娘の詐称疑惑と苦悩と情熱。", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "2Flc3k6n6W0", "SLAVE.V-V-R feat.Fantastic Youth", ORIGINAL_TRACK, OTHER_THEME],
	["コモリの怪物", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "DYigt0kDoIU", "盛るP feat.鈴森あおい", ORIGINAL_TRACK, OTHER_THEME],
	["中学2年生のアンドロイド", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "Ynn70bBP9uw", "カルロス袴田(サイゼP) feat.あやぽんず＊", ORIGINAL_TRACK, OTHER_THEME],
	["Life", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "fChrmsVK5vE", "Relect", ORIGINAL_TRACK, OTHER_THEME],
	["Solstånd", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "zP6O_Km7fXc", "Rigel Theatre feat.ミーウェル", ORIGINAL_TRACK, OTHER_THEME],
	["Sqlupp", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "X5tNUpDx_9Q", "owl＊tree feat.yaki＊tree", ORIGINAL_TRACK, OTHER_THEME],
	["Climax", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "rkw5jFDaEFM", "USAO", ORIGINAL_TRACK, OTHER_THEME],
	["Innocent Truth", new Set([TITLE.AMAZON]), { title: "AMAZON" }, "yqbtUxVCZY4", "Endorfin.", ORIGINAL_TRACK, OTHER_THEME],
	["エンジェデビ", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "AKXz97tmVlA", "中路もとめ feat.砂糖子", ORIGINAL_TRACK, OTHER_THEME],
	["Servant of Love", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "kwOo3RZazxA", "PandaBoY", ORIGINAL_TRACK, OTHER_THEME],
	["アイリちゃんは暗黒魔導士!", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "ZhssI4glYJM", "MOSAIC.WAV", ORIGINAL_TRACK, OTHER_THEME],
	["電光石火", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "qRYm-lSAhDo", "HiTECH NINJA", ORIGINAL_TRACK, OTHER_THEME],
	["strelitzia", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "S4LKCAQ5WYw", "zts", ORIGINAL_TRACK, OTHER_THEME],
	["恋のチャイム", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "FB2b5i6aYCk", "霜月はるか", ORIGINAL_TRACK, OTHER_THEME],
	["逃げろ！サテライトキャンパス！！", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "LoyVaEGWYmc", "solfa feat.茶太", ORIGINAL_TRACK, OTHER_THEME],
	["THE BRASS OF GOODSPEED!!", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "dDqxUUvwITY", "片霧烈火", ORIGINAL_TRACK, OTHER_THEME],
	["暗晦にハイライト", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "10_KuiLNtbE", "igel", ORIGINAL_TRACK, OTHER_THEME],
	["8-EM", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "H_969oyRM9k", "Sampling Masters AYA", ORIGINAL_TRACK, OTHER_THEME],
	["Killing Rhythm", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "58ZS-SLqTDI", "DJ Myosuke", ORIGINAL_TRACK, OTHER_THEME],
	["ユメキキョウ", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "uXHmuL_zKlc", "RD-Sounds feat.中恵光城", ORIGINAL_TRACK, OTHER_THEME],
	["Black Swan Lake", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "uaaOb-6-kns", "葉月ゆら", ORIGINAL_TRACK, OTHER_THEME],
	["GIGA DRIVE", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "umsyNjrCHmA", "黒沢ダイスケ", ORIGINAL_TRACK, OTHER_THEME],
	["Rebellion", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "NGiEMbOQ-Js", "Kai", ORIGINAL_TRACK, OTHER_THEME],
	["Vibrant Verve", new Set([TITLE.AMAZON_PLUS]), { title: "AMAZON_PLUS" }, "Ed98AjTprcA", "siqlo", ORIGINAL_TRACK, OTHER_THEME],
	["神威 (NAOKI × ZPP MIX)", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "1RmWoBcVqjM", "NAOKI MAEDA", ORIGINAL_TRACK, OTHER_THEME],
	["サヴァイバル・キリング・メーカー", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "aUTpE24S2qs", "じーざす（ワンダフル☆オポチュニティ！） ft.96猫", ORIGINAL_TRACK, OTHER_THEME],
	["ツクヨミステップ", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "py2lVCmGxLc", "ユリイ・カノン feat.nameless", ORIGINAL_TRACK, OTHER_THEME],
	["【冒険】イングリット葛西降臨！【実況】", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "Nki7yIil1l0", "溝口ゆうま axel. 大瀬良あい", ORIGINAL_TRACK, OTHER_THEME],
	["ハジマリノピアノ", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "d6ijNKIwLgY", "ゆゆうた", ORIGINAL_TRACK, OTHER_THEME],
	["レーイレーイ", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "puvZvcrb5VQ", "かいりきベア feat.松下", ORIGINAL_TRACK, OTHER_THEME],
	["Surrogate Life", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "58eZTwEeqDU", "石渡太輔／アークシステムワークス", ORIGINAL_TRACK, OTHER_THEME],
	["Nijirate Fanatics", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "lcDtHA1JH9w", "yukitani", ORIGINAL_TRACK, OTHER_THEME],
	["せかいせいふく！ゆりあちゃん！", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "QQvIKP41XEE", "立秋", ORIGINAL_TRACK, OTHER_THEME],
	["Trackless wilderness", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "juBZl8VVF0Y", "Noah", ORIGINAL_TRACK, OTHER_THEME],
	["absolute rightness", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "vwHT6uW2RRc", "Acotto", ORIGINAL_TRACK, OTHER_THEME],
	["Walzer für das Nichts", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "dnim2l7p6qM", "Aoi Sumito", ORIGINAL_TRACK, OTHER_THEME],
	["Lover's Trick", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "fxRO7v8pvxc", "litmus*", ORIGINAL_TRACK, OTHER_THEME],
	["まごころのカスクルゥト", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "vmE_5wZtdww", "Yu-dachi", ORIGINAL_TRACK, OTHER_THEME],
	["《混乱》 ～ Muspell", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "SVOXtvSe0Nk", "Norn", ORIGINAL_TRACK, OTHER_THEME],
	["《理想》 ～ Cloudland", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "C8dji7oOqkU", "Shi Kuang Lee feat.A-Tz", ORIGINAL_TRACK, OTHER_THEME],
	["《逃避》 ～ The Deserter", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "QzrlT1pWUpM", "Bo-Xun Lin 林柏勲", ORIGINAL_TRACK, OTHER_THEME],
	["《最愛》 ～ Curse", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "fNYcuGKbBVg", "James Landino feat.N i i", ORIGINAL_TRACK, OTHER_THEME],
	["《運命》 ～ Ray of Hope", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "gtQ5i8wgGiM", "3R2", ORIGINAL_TRACK, OTHER_THEME],
	["とーきょー全域★アキハバラ？ (ver.にこる)", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "-uvo_tyW16I", "MOSAIC.WAV／t+pazolite feat.ななひら", ORIGINAL_TRACK, OTHER_THEME],
	["ヴンダーカンマー", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "jqHTbYAXe8g", "麹町養蚕館", ORIGINAL_TRACK, OTHER_THEME],
	["Destination", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "-gWPR4c3ZHM", "Nhato", ORIGINAL_TRACK, OTHER_THEME],
	["Fidget Dancer", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "lTAlden4YCA", "nora2r", ORIGINAL_TRACK, OTHER_THEME],
	["Megameteor", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "1iOnjwUVTWo", "削除", ORIGINAL_TRACK, OTHER_THEME],
	["Trrricksters!!", new Set([TITLE.CRYSTAL]), { title: "CRYSTAL" }, "_GeIahZk31I", "s-don vs. 翡乃イスカ", ORIGINAL_TRACK, OTHER_THEME],
	["Ghost Dance", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "fDcpikvBVrU", "亜沙 feat.くろくも", ORIGINAL_TRACK, OTHER_THEME],
	["モノクロトワイライト", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "aLFcYgxmels", "カラフル・サウンズ・ポート", ORIGINAL_TRACK, OTHER_THEME],
	["シャッキーーン！！", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "AJQOpo_9gb0", "黒魔", ORIGINAL_TRACK, OTHER_THEME],
	["《破滅》 ～ Rhapsody for The End", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "lUZPZR8LfYE", "Spiegel vs Ice", ORIGINAL_TRACK, OTHER_THEME],
	["ロング・スロー・アライブ", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "c2-TZKTijHU", "はるまきごはん feat.めらみぽっぷ", ORIGINAL_TRACK, OTHER_THEME],
	["迷える薔薇に終わらぬ夜を", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "KGiUePslObM", "YM feat.かんせる", ORIGINAL_TRACK, OTHER_THEME],
	["パームカルマ", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "quKRcTmtE04", "ポリスピカデリー feat.相宮零", ORIGINAL_TRACK, OTHER_THEME],
	["Therapeutic Hoedown", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "8K1AXrSc6m0", "うどんゲルゲ", ORIGINAL_TRACK, OTHER_THEME],
	["Jörqer", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "LrQpTz6TZ6I", "owl＊tree feat.yu＊tree", ORIGINAL_TRACK, OTHER_THEME],
	["ちゅんちゅちゅチューン", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "oU4zGZo0r5I", "さつき が てんこもり feat.kana", ORIGINAL_TRACK, OTHER_THEME],
	["ドルオタ忍道！楠子ノ巻", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "hc2Rcu_XxRM", "コバヤシユウヤ（IOSYS） feat.You-Re:", ORIGINAL_TRACK, OTHER_THEME],
	["エキセントリックコンコン", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "gAfN9fMee1w", "Clean Tears feat.kukuri", ORIGINAL_TRACK, OTHER_THEME],
	["大天使ユリア★降臨!", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "nBiWq1HFm40", "MOSAIC.WAV", ORIGINAL_TRACK, OTHER_THEME],
	["U ARE", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "JlIk9pP7Fds", "MK&Kanae Asaba", ORIGINAL_TRACK, OTHER_THEME],
	["ハードコア・シンドローム", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "aWvODcYc1ak", "t+pazolite (HARDCORE TANO*C) feat.TANO*C ALL STARS", ORIGINAL_TRACK, OTHER_THEME],
	["Hainuwele", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "PBtoPb6D4MY", "ETIA.", ORIGINAL_TRACK, OTHER_THEME],
	["宿星審判", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "VxPRLDQvz8Y", "suzu", ORIGINAL_TRACK, OTHER_THEME],
	["The Metaverse -First story of the SeelischTact-", new Set([TITLE.CRYSTAL_PLUS]), { title: "CRYSTAL_PLUS" }, "oG6-1SQ_SuQ", "光吉猛修 VS 目黒将司", ORIGINAL_TRACK, OTHER_THEME],
	["テリトリーバトル", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "ytrDJFCv8tI", "ツユ", ORIGINAL_TRACK, OTHER_THEME],
	["ROAD TO DREAM", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "TTl_WHgueic", "達見 恵 featured by 佐野宏晃", ORIGINAL_TRACK, OTHER_THEME],
	["絶対トキメキデリバリー", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "3HEVmi7vYe8", "TOKOTOKO（西沢さんP） feat.あやぽんず＊", ORIGINAL_TRACK, OTHER_THEME],
	["Yume no hajimari", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "iEND99FniZ4", "Virtual Cat", ORIGINAL_TRACK, OTHER_THEME],
	["Hey Yeah!!", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "diYUh_LWAHc", "KOTONOHOUSE", ORIGINAL_TRACK, OTHER_THEME],
	["B100d Hunter", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "WTsMOrXCDb0", "DIVELA feat.いゔどっと", ORIGINAL_TRACK, OTHER_THEME],
	["Last Celebration", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "O5f6H2ZaqFc", "Laur vs CK", ORIGINAL_TRACK, OTHER_THEME],
	["Paqqin (tpz Despair Remix)", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "Dhh9zTu_MXI", "owl＊tree／t+pazolite", ORIGINAL_TRACK, OTHER_THEME],
	["宙の隣", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "Nij8d2sS-zc", "くるぶっこちゃん", ORIGINAL_TRACK, OTHER_THEME],
	["Just You", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "vYNltV69eXk", "サルケバ", ORIGINAL_TRACK, OTHER_THEME],
	["Insane Gamemode", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "AnLeH4pljZo", "pan vs 7mai", ORIGINAL_TRACK, OTHER_THEME],
	["Parad'ox", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "_zSUFJFvD80", "Potwi", ORIGINAL_TRACK, OTHER_THEME],
	["ANU", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "toshKgN1HcA", "sasakure.UK VS 穴山大輔", ORIGINAL_TRACK, OTHER_THEME],
	["《狂乱》 ～ Cataclysm", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "rJTIH8cTOao", "3R2 as Katzeohr", ORIGINAL_TRACK, OTHER_THEME],
	["《投影》 ～ Oh My Baby Doll", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "ENBseJ3w_ks", "Ring feat.SLSMusic", ORIGINAL_TRACK, OTHER_THEME],
	["《信仰》 ～ Eudaimonia", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "9AlHcO8F7D0", "空氣載體 The AirCarrier", ORIGINAL_TRACK, OTHER_THEME],
	["《選別》 ～ Refuge", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "ail-7KBz0cE", "Iris", ORIGINAL_TRACK, OTHER_THEME],
	["《本能》 ～ ReCoda", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "o5kiIEJxLyE", "Spiegel vs Yukino", ORIGINAL_TRACK, OTHER_THEME],
	["赤壁、大炎上！！", new Set([TITLE.PARADISE]), { title: "PARADISE" }, "n3W0_CQLysI", "Cranky feat.おもしろ三国志", ORIGINAL_TRACK, OTHER_THEME],
	["レイニーカラー・ウォーターカラー", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "OJXNqIupB-w", "烏屋茶房 feat.利香", ORIGINAL_TRACK, OTHER_THEME],
	["おいでよ！ 高須らいむランド", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "sWcauHMvkoU", "柏木るざりん feat.青葉りんご", ORIGINAL_TRACK, OTHER_THEME],
	["Charlatan", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "amMm8YnK0yk", "煮ル果実×びす", ORIGINAL_TRACK, OTHER_THEME],
	["萌豚♥功夫♥大乱舞", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "RTe1-80vqs0", "李 龟琍椏 feat.娜娜苤來", ORIGINAL_TRACK, OTHER_THEME],
	["つっぱれ！にゃんきー魂", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "dezCHlw_bXI", "Neko Hacker feat.うごくちゃん", ORIGINAL_TRACK, OTHER_THEME],
	["Athlete Killer \"Meteor\"", new Set([TITLE.NEW]), { title: "NEW" }, "1zpcaCifeYU", "LamazeP feat.月乃", ORIGINAL_TRACK, OTHER_THEME],
	["Blazing:Storm", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "svmgYJ_hVoo", "かゆき", ORIGINAL_TRACK, OTHER_THEME],
	["C & B", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "d8ZLSFOOJGQ", "PSYQUI feat.Such", ORIGINAL_TRACK, OTHER_THEME],
	["月詠に鳴る", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "KT-DtJWCLMA", "Feryquitous feat.藍月なくる", ORIGINAL_TRACK, OTHER_THEME],
	["Blessed Rain", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "IgCjgGf4OlQ", "ぺのれり", ORIGINAL_TRACK, OTHER_THEME],
	["Elemental Ethnic", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "WtP9JoiUZeA", "Yooh", ORIGINAL_TRACK, OTHER_THEME],
	["X7124", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "wKCNWTuHOSU", "Silentroom", ORIGINAL_TRACK, OTHER_THEME],
	["祈 -我ら神祖と共に歩む者なり-", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "o6Lu9Q8_UI4", "光吉猛修 VS 穴山大輔 VS Kai VS 水野健治 VS 大国奏音", ORIGINAL_TRACK, OTHER_THEME],
	["[CRYSTAL_ACCESS]", new Set([TITLE.NEW]), { title: "NEW" }, "W-r3RwGp82A", "Blacklolita", ORIGINAL_TRACK, OTHER_THEME],
	["TECHNOPOLIS 2085", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "6g0UNVLlzBQ", "PRASTIK DANCEFLOOR", ORIGINAL_TRACK, OTHER_THEME],
	["ハルシナイト", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "ko45woyDggc", "かしこ。 feat.Cereus", ORIGINAL_TRACK, OTHER_THEME],
	["Dark Diver", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "iNOru9cx-Ok", "emon(Tes.) feat.ねんね", ORIGINAL_TRACK, OTHER_THEME],
	["Tattoo", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "9iUBRT-ZYsw", "みきとP feat. victream", ORIGINAL_TRACK, OTHER_THEME],
	["呪歌-JyuKa-", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "JalVbzg2Izs", "ガルナ(オワタP) feat.水槽", ORIGINAL_TRACK, OTHER_THEME],
	["再生不能", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "Cwsxu1R0QIY", "ろくろ feat.鹿乃", ORIGINAL_TRACK, OTHER_THEME],
	["UltraNeon", new Set([TITLE.NEW]), { title: "NEW" }, "LGhbQY74ihY", "eoll", ORIGINAL_TRACK, OTHER_THEME],
	["雪男", new Set([TITLE.NEW]), { title: "NEW" }, "ARBrOpScJ8M", "かねこちはる", ORIGINAL_TRACK, OTHER_THEME],
	["DDDD", new Set([TITLE.NEW]), { title: "NEW" }, "Eb2HZsWgTTc", "monaca:factory feat.NORISTRY", ORIGINAL_TRACK, OTHER_THEME],
	["Ring", new Set([TITLE.NEW]), { title: "NEW" }, "jiTt1IPbtpc", "R Sound Design feat.向日葵", ORIGINAL_TRACK, OTHER_THEME],
	["Blazing Break", new Set([TITLE.NEW]), { title: "NEW" }, "hKXe0S89EHM", "yksb feat.MiLO", ORIGINAL_TRACK, OTHER_THEME],
	["Give me Love♡", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "T_1Nof0_X0g", "C.G mix feat. RINA", ORIGINAL_TRACK, OTHER_THEME],
	["Crack", new Set([TITLE.NEW]), { title: "NEW" }, "f9BcDc2XZSM", "はるなば feat.すずしろ", ORIGINAL_TRACK, OTHER_THEME],
	["STAR IN THE WORLD", new Set([TITLE.NEW]), { title: "NEW" }, "PMjm_0oQZ7U", "片霧烈火", ORIGINAL_TRACK, OTHER_THEME],
	["蜘蛛の糸", new Set([TITLE.NEW]), { title: "NEW" }, "p0y6uhyorvs", "きくお×cosMo＠暴走P feat.影縫英", ORIGINAL_TRACK, OTHER_THEME],
	["コスモポップファンクラブ", new Set([TITLE.NEW]), { title: "NEW" }, "ysr1AS22pXc", "ナユタン星人", ORIGINAL_TRACK, OTHER_THEME],
	["夢路拍子", new Set([TITLE.NEW]), { title: "NEW" }, "NtrrPGkf95E", "稲葉曇 feat.Rairu", ORIGINAL_TRACK, OTHER_THEME],
	["人生攻略☆Tips", new Set([TITLE.NEW]), { title: "NEW" }, "1x4c3HZsTMs", "れるりり feat.konoco", ORIGINAL_TRACK, OTHER_THEME],
	["ピュグマリオンの咒文", new Set([TITLE.NEW]), { title: "NEW" }, "cZ3q7fn-gFY", "アリスシャッハと魔法の楽団", ORIGINAL_TRACK, OTHER_THEME],
	["創世のコンツェルティーナ", new Set([TITLE.NEW]), { title: "NEW" }, "ogqOXD0NzUM", "大嶋啓之", ORIGINAL_TRACK, OTHER_THEME],
	["Fantasm", new Set([TITLE.NEW]), { title: "NEW" }, "02cKRmgR1o4", "yuigot feat.菅野真衣", ORIGINAL_TRACK, OTHER_THEME],
	["Echoes", new Set([TITLE.NEW]), { title: "NEW" }, "wuRyqM_s8Hc", "Aiobahn", ORIGINAL_TRACK, OTHER_THEME],
	["Super Kitsch Mode", new Set([TITLE.NEW]), { title: "NEW" }, "UeCcAyjHxSE", "Avec Avec", ORIGINAL_TRACK, OTHER_THEME],
	["Pre Paid Pog Punk Panic", new Set([TITLE.NEW]), { title: "NEW" }, "HVfyUKbIt50", "Hercelot", ORIGINAL_TRACK, OTHER_THEME],
	["自分勝手Dazzling", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "-n9VNs5LSrE", "星街すいせい（ホロライブ）", ORIGINAL_TRACK, OTHER_THEME],
	["Utopithm", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "oIF3MG-fSCQ", "memex", ORIGINAL_TRACK, OTHER_THEME],
	["妖怪ですから", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "26FCMEF89so", "ぼっちぼろまる", ORIGINAL_TRACK, OTHER_THEME],
	["Glory Days", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "UHkpZKl9TGU", "KMNZ", ORIGINAL_TRACK, OTHER_THEME],
	["Spiral Fortune", new Set([TITLE.PARADISE_LOST]), { title: "PARADISE_LOST" }, "oFWPZZBYFKI", "Marpril", ORIGINAL_TRACK, OTHER_THEME],
	["《自戒》 ～ Paganelope", new Set([TITLE.NEW]), { title: "NEW" }, "7gFoLHThvAM", "Warak", ORIGINAL_TRACK, OTHER_THEME],
	["《紀律》 ～ As One", new Set([TITLE.NEW]), { title: "NEW" }, "G1dXwa_PPww", "James Landino feat.Nikki Simmons", ORIGINAL_TRACK, OTHER_THEME],
	["《種子》 ～ Set You Free", new Set([TITLE.NEW]), { title: "NEW" }, "emvuMhEvJi8", "Iris", ORIGINAL_TRACK, OTHER_THEME],
	["《偏愛》 ～ Shattered Memories", new Set([TITLE.NEW]), { title: "NEW" }, "YgZHQVkbdB4", "3R2", ORIGINAL_TRACK, OTHER_THEME],
	["Qliphothgear", new Set([TITLE.NEW]), { title: "NEW" }, "6dLQxhrmOZE", "Juggernaut.", ORIGINAL_TRACK, OTHER_THEME],
	["SQUAD-Phvntom-", new Set([TITLE.NEW]), { title: "NEW" }, "Dhl2yzSITaA", "Getty vs DJ DiA", ORIGINAL_TRACK, OTHER_THEME],
	["parvorbital", new Set([TITLE.NEW]), { title: "NEW" }, "CF8U2mGECDY", "Frums", ORIGINAL_TRACK, OTHER_THEME],
	["Inpaqq", new Set([TITLE.NEW]), { title: "NEW" }, "Qi3F8uH1iiM", "owl＊tree feat. ka＊tree", ORIGINAL_TRACK, OTHER_THEME],
	["Strange Love", new Set([TITLE.NEW]), { title: "NEW" }, "8XZ4Okh27WI", "削除", ORIGINAL_TRACK, OTHER_THEME],
	["IMPACT", new Set([TITLE.NEW]), { title: "NEW" }, "yLWl25bgIw0", "USAO feat.光吉猛修", ORIGINAL_TRACK, OTHER_THEME],
	["POTENTIAL", new Set([TITLE.NEW]), { title: "NEW" }, "zCoD5LtJHoE", "TAG", ORIGINAL_TRACK, OTHER_THEME],
	["タイムカプセル", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "GrbmCDt6qMc", "天月-あまつき-", ORIGINAL_TRACK, OTHER_THEME],
	["パズルリボン", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "O0pJQto65vk", "すりぃ feat.りょーくん", ORIGINAL_TRACK, OTHER_THEME],
	["Be4Step", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "vHjINrlv0PE", "tilt-six feat.バル", ORIGINAL_TRACK, OTHER_THEME],
	["Everlasting Liberty", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "Aj70--EgWqg", "Kobaryo", ORIGINAL_TRACK, OTHER_THEME],
	["愛のシンギュラリティ", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "u-x4r11hfDA", "yuichi NAGAO", ORIGINAL_TRACK, OTHER_THEME],
	["アナタニナルノ", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "K_tKhAlv_9I", "FANTAGIRAFF", ORIGINAL_TRACK, OTHER_THEME],
	["I'll make you Super Rock Star", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "mhZwUMw6UFE", "かぼちゃ", ORIGINAL_TRACK, OTHER_THEME],
	["Reverberate", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "5ahiAAgasaI", "とろまる", ORIGINAL_TRACK, OTHER_THEME],
	["Breakthrough", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "yhYHpkWoOms", "Aiko Oi", ORIGINAL_TRACK, OTHER_THEME],
	["Scythe of Death", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "UjdajzRG8TE", "Masahiro \"Godspeed\" Aoki", ORIGINAL_TRACK, OTHER_THEME],
	["#SUP3RORBITAL", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "8bZNT36TqdU", "ああ…翡翠茶漬け…", ORIGINAL_TRACK, OTHER_THEME],
	["WE'RE BACK!!", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "nB-0u5Tn2Fo", "Zekk", ORIGINAL_TRACK, OTHER_THEME],
	["Brightness", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "Bq-aDyfUTwA", "Masayoshi Iimori", ORIGINAL_TRACK, OTHER_THEME],
	["Λzure Vixen", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "UFSjVgQr8TE", "かめりあ", ORIGINAL_TRACK, OTHER_THEME],
	["MALKUTH -The Last Ruler of Terrestrials-", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "Q2M_do6QhAw", "穴山大輔 VS 光吉猛修", ORIGINAL_TRACK, OTHER_THEME],
	["DA'AT -The First Seeker of Souls-", new Set([TITLE.NEW_PLUS]), { title: "NEW_PLUS" }, "fCsP0tgfcMw", "水野健治 VS 大国奏音", ORIGINAL_TRACK, OTHER_THEME],
	["インパアフェクシオン・ホワイトガアル", new Set([TITLE.SUN]), { title: "SUN" }, "VLxTXJngUiY", "ツミキ feat.月乃", ORIGINAL_TRACK, OTHER_THEME],
	["クリーパー", new Set([TITLE.SUN]), { title: "SUN" }, "HDfOgQV69nE", "遼遼 feat.あじっこ", ORIGINAL_TRACK, OTHER_THEME],
	["Ignition", new Set([TITLE.SUN]), { title: "SUN" }, "I3omVxJoySM", "パソコン音楽クラブ", ORIGINAL_TRACK, OTHER_THEME],
	["推してもダメならひいてみな！", new Set([TITLE.SUN]), { title: "SUN" }, "TIYuqO9OC3A", "桃井はるこ", ORIGINAL_TRACK, OTHER_THEME],
	["ガチ恋ラビリンス", new Set([TITLE.SUN]), { title: "SUN" }, "ii4mKbPv5fk", "森羅万象", ORIGINAL_TRACK, OTHER_THEME],
	["CELERITAS", new Set([TITLE.SUN]), { title: "SUN" }, "IMqtTeFM5uA", "山本真央樹", ORIGINAL_TRACK, OTHER_THEME],
	["グラウンドスライダー協奏曲第一番「風唄」", new Set([TITLE.SUN]), { title: "SUN" }, "x_7qZWUWrIA", "削除", ORIGINAL_TRACK, OTHER_THEME],
	["Crawler / Flyer", new Set([TITLE.SUN]), { title: "SUN" }, "AR66yfJvvXY", "MaiR", ORIGINAL_TRACK, OTHER_THEME],
	["Re:Credits", new Set([TITLE.SUN]), { title: "SUN" }, "aTcAJ7WToI0", "BOOGEY VOXX feat.IURA TOI", ORIGINAL_TRACK, OTHER_THEME],
	["Cheat Sheet", new Set([TITLE.SUN]), { title: "SUN" }, "USnb1TIWnTE", "Yaca × gaburyu", ORIGINAL_TRACK, OTHER_THEME],
	["One Room Sky", new Set([TITLE.SUN]), { title: "SUN" }, "9Cbv5RNYzeY", "MonsterZ MATE", ORIGINAL_TRACK, OTHER_THEME],
	["任せてJC陰陽師☆八雲ちゃん", new Set([TITLE.SUN]), { title: "SUN" }, "E4LOcIidkPM", "永倉秋斗 feat.キャサリン", ORIGINAL_TRACK, OTHER_THEME],
	["†大闘士＝クライン・フォーゲル・シュピール＝えりか†", new Set([TITLE.SUN]), { title: "SUN" }, "jR6kJxAyyR4", "立秋 feat.ちょこ", ORIGINAL_TRACK, OTHER_THEME],
	["Fallin' Darlin' Rollin'", new Set([TITLE.SUN]), { title: "SUN" }, "qW9NnF_UNrc", "ave;new feat.佐倉紗織", ORIGINAL_TRACK, OTHER_THEME],
	["恋するみたいに☆かませレッドヘルズ", new Set([TITLE.SUN]), { title: "SUN" }, "SNvZSe6Hq7M", "コバヤシユウヤ（IOSYS） feat.miko", ORIGINAL_TRACK, OTHER_THEME],
	["盟月", new Set([TITLE.SUN]), { title: "SUN" }, "rr4BruVyMXg", "打打だいず", ORIGINAL_TRACK, OTHER_THEME],
	["Bitter Juicy", new Set([TITLE.SUN]), { title: "SUN" }, "tWSgRofc1HU", "mommy", ORIGINAL_TRACK, OTHER_THEME],
	["Disruptor Array", new Set([TITLE.SUN]), { title: "SUN" }, "sRwdpgSo5XY", "Akira Complex vs kiraku", ORIGINAL_TRACK, OTHER_THEME],
	["Daphnis", new Set([TITLE.SUN]), { title: "SUN" }, "goFEmrr6sqI", "Sobrem a.k.a. Widowmaker", ORIGINAL_TRACK, OTHER_THEME],
	["To：Be Continued", new Set([TITLE.SUN]), { title: "SUN" }, "fah5f7-zu0k", "uma vs. ガリガリさむし", ORIGINAL_TRACK, OTHER_THEME],
	["4月1日でございました", new Set([TITLE.SUN]), { title: "SUN" }, "Pe425j7kueo", "Cranky", ORIGINAL_TRACK, OTHER_THEME],
	["ウルガレオン", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "-oYxZ0ncBBY", "bermei.inazawa", ORIGINAL_TRACK, OTHER_THEME],
	["やめらんないな!", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "vx4HwGAS5vg", "薄塩指数 feat.KMNZ LIZ", ORIGINAL_TRACK, OTHER_THEME],
	["Dive a Wave", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "6mSdIEQRhuE", "蝶々P feat.くろくも", ORIGINAL_TRACK, OTHER_THEME],
	["ASH", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "sYtV1SgzmZw", "cubesato", ORIGINAL_TRACK, OTHER_THEME],
	["Makear", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "_gKVMupgCIk", "MisoilePunch♪", ORIGINAL_TRACK, OTHER_THEME],
	["うたかたのせかいで", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "r4BI9xkp2bc", "DJ Raisei vs. Setca. feat.nayuta", ORIGINAL_TRACK, OTHER_THEME],
	["とあちゃんのおもちゃ箱", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "UoeJ2CH9y2Y", "linear ring", ORIGINAL_TRACK, OTHER_THEME],
	["白庭", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "zfwn86RxYg4", "くるぶっこちゃん", ORIGINAL_TRACK, OTHER_THEME],
	["REL0VE REL1VE", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "UiJy2pGDp7U", "CHUBAY×打打だいず", ORIGINAL_TRACK, OTHER_THEME],
	["deadeye", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "DPJrFL9gN7s", "Acotto", ORIGINAL_TRACK, OTHER_THEME],
	["夢と幻想の終点にて", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "2oR4_jiSAZA", "しーけー", ORIGINAL_TRACK, OTHER_THEME],
	["Superbia", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "dpjwvVK3e_E", "Team Grimoire", ORIGINAL_TRACK, OTHER_THEME],
	["空間創造理論", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "F_NtOGKInWY", "Sound piercer", ORIGINAL_TRACK, OTHER_THEME],
	["βlαnoir", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "I4I9br1d_sA", "Aoi", ORIGINAL_TRACK, OTHER_THEME],
	["《真紅》 ～ Pavane Pour La Flamme", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "BvzyXZROU-4", "林柏勲 Bo-Xun Lin feat.幻子 Maboroshiko", ORIGINAL_TRACK, OTHER_THEME],
	["《楽土》 ～ One and Only One", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "W1odKycITzw", "Victor Kong & Yukino", ORIGINAL_TRACK, OTHER_THEME],
	["《散華》 ～ EMBARK", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "SL2EQT_-LgI", "Farhan Sarasin", ORIGINAL_TRACK, OTHER_THEME],
	["《慈雨》 ～ La Symphonie de Salacia: Agony Movement", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "4YbuoBXHm14", "Jehezukiel (feat.Sagi & KURORAK)", ORIGINAL_TRACK, OTHER_THEME],
	["《創造》 ～ Cries, beyond The End", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "Da5uJiMdhIY", "Katzeohr & Spiegel", ORIGINAL_TRACK, OTHER_THEME],
	["Chaotic Ørder", new Set([TITLE.SUN_PLUS]), { title: "SUN_PLUS" }, "xHOF0AZRWu4", "TAG VS Kai", ORIGINAL_TRACK, OTHER_THEME],
	["少女PastQ", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "Q8XB06Jx57w", "雄之助 feat.ねんね", ORIGINAL_TRACK, OTHER_THEME],
	["君と夏色っ！～わんダフルバケーション～", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "qTy2EtfrbUE", "コバヤシユウヤ（IOSYS） feat.まるもこ", ORIGINAL_TRACK, OTHER_THEME],
	["MyPaceInvention", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "CpgNyRkmG2Y", "キツネリ feat.わかばやし", ORIGINAL_TRACK, OTHER_THEME],
	["colorful", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "UII5AU7Yd5w", "higma feat.ほとけ", ORIGINAL_TRACK, OTHER_THEME],
	["ZegalltA", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "QhUl-Rj3T1E", "Se-U-Ra", ORIGINAL_TRACK, OTHER_THEME],
	["ウニの歌", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "f_Dcq7lkWC4", "周防パトラ", ORIGINAL_TRACK, OTHER_THEME],
	["驚異の魔法", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "KCjRw30n3N0", "長瀬有花", ORIGINAL_TRACK, OTHER_THEME],
	["liberate", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "_vR4FMAP06s", "somunia × nyankobrq", ORIGINAL_TRACK, OTHER_THEME],
	["lucky omen", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "AEmA-LobfVQ", "TEMPLIME feat.星宮とと", ORIGINAL_TRACK, OTHER_THEME],
	["Sunlight Starlight", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "zxVdKRaPfDA", "Palme", ORIGINAL_TRACK, OTHER_THEME],
	["ワーカーホリック", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "B_xslEDq8_I", "ミディ feat.小鈴", ORIGINAL_TRACK, OTHER_THEME],
	["Overturn", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "FHgHNenNRYw", "Mameyudoufu feat.Kanata.N", ORIGINAL_TRACK, OTHER_THEME],
	["First Light", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "An_JOvAr6hc", "Carpainter", ORIGINAL_TRACK, OTHER_THEME],
	["ラストピースに祝福と栄光を", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "q-KYjXNALlc", "cosMo＠暴走P", ORIGINAL_TRACK, OTHER_THEME],
	["crazy (about you)", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "WC1671lngAQ", "kamome sano", ORIGINAL_TRACK, OTHER_THEME],
	["Dèfandour", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "ZGWClONVI9Q", "BlackY", ORIGINAL_TRACK, OTHER_THEME],
	["Ultimate Force", new Set([TITLE.LUMINOUS]), { title: "LUMINOUS" }, "5Gfq5QqDtzE", "削除", ORIGINAL_TRACK, OTHER_THEME],
	["バッドトリッパー", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "J3pwf8bP9Oc", "マイキP", ORIGINAL_TRACK, OTHER_THEME],
	["幻想ロードオブキング", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "6B4X2F57z_E", "DJ SHARPNEL feat. 相川なつ", ORIGINAL_TRACK, OTHER_THEME],
	["イーヴィルガール", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "aqFWgyqmMEY", "Fushi feat.吉乃", ORIGINAL_TRACK, OTHER_THEME],
	["わたしはオッセルヴァトリーチェ！", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "cSa4b3W3i6I", "アオワイファイ feat.秋山雫", ORIGINAL_TRACK, OTHER_THEME],
	["優勝Princess♡", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "qXTXMuAVpEk", "高瀬一矢 feat.R.I.N.A", ORIGINAL_TRACK, OTHER_THEME],
	["リ・フィクション・O", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "stsHg_Oslqk", "sasakure.UK feat.ピリオ", ORIGINAL_TRACK, OTHER_THEME],
	["DRE4M1N9", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "uHEaMvNOAIw", "Lamanya", ORIGINAL_TRACK, OTHER_THEME],
	["Overhea[r]t", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "aASd6j-8BaI", "打打だいず", ORIGINAL_TRACK, OTHER_THEME],
	["Malleus Maleficarum", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "c8tffiXxtdw", "Felysrator", ORIGINAL_TRACK, OTHER_THEME],
	["Elusive Enforcer", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "N55X5UjXgJA", "K-forest vs. Reku Mochizuki", ORIGINAL_TRACK, OTHER_THEME],
	["黎命に殉ず", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "bxemIuwB1iY", "Koke", ORIGINAL_TRACK, OTHER_THEME],
	["X.Y.Z.", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "s94e3BvVB1k", "Len feat.SHIKI", ORIGINAL_TRACK, OTHER_THEME],
	["コメクエスト", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "p9_3uZF2g7A", "ELEMENTAS feat.miko", ORIGINAL_TRACK, OTHER_THEME],
	["乙女戦士☆あーし。", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "w2HjiQNyh88", "A4。 feat.yamada.", ORIGINAL_TRACK, OTHER_THEME],
	["おしゃまなプリンセス", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "oX4k374JZeo", "Shu feat. 七海うらら", ORIGINAL_TRACK, OTHER_THEME],
	["ソーシャルワンダーランド", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "IXTpKRH-cUc", "テヅカ x Aoi feat.すずしろ", ORIGINAL_TRACK, OTHER_THEME],
	["Lovely Lovely Lover", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "fD2vPO2GF9A", "EmoCosine", ORIGINAL_TRACK, OTHER_THEME],
	["Fire Engine73", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "ypkK4EJlSEo", "AJURIKA", ORIGINAL_TRACK, OTHER_THEME],
	["LibrariA", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "P4lGw-O1iqY", "ルゼ", ORIGINAL_TRACK, OTHER_THEME],
	["Tuatha Dé Danann", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "1JEda9ugnII", "深淵を覗きし者\"Gram\"", ORIGINAL_TRACK, OTHER_THEME],
	["Acid God", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "M51KjS105p4", "Yuta Imai", ORIGINAL_TRACK, OTHER_THEME],
	["Forsaken Tale", new Set([TITLE.LUMINOUS_PLUS]), { title: "LUMINOUS_PLUS" }, "uBjxgZGVoIE", "t+pazolite", ORIGINAL_TRACK, OTHER_THEME],
	["メッちゅう殴打", new Set([TITLE.VERSE]), { title: "VERSE" }, "2csRyv-f5-s", "STEAKA feat.山田じぇみ子", ORIGINAL_TRACK, OTHER_THEME],
	["ドリームケッチャー", new Set([TITLE.VERSE]), { title: "VERSE" }, "O9DUfFwC8Q8", "OUTLOUD feat.NG。", ORIGINAL_TRACK, OTHER_THEME],
	["ラブリージャッジメント", new Set([TITLE.VERSE]), { title: "VERSE" }, "aJDDY3lnnyQ", "いるかアイス feat.ちょこ", ORIGINAL_TRACK, OTHER_THEME],
	["房総★ミラクル☆てんたくる!?", new Set([TITLE.VERSE]), { title: "VERSE" }, "0R5-jNon7Lg", "MOSAIC.WAV", ORIGINAL_TRACK, OTHER_THEME],
	["Crystallize", new Set([TITLE.VERSE]), { title: "VERSE" }, "XjTe55VOZVk", "Lime", ORIGINAL_TRACK, OTHER_THEME],
	["Oracle", new Set([TITLE.VERSE]), { title: "VERSE" }, "qhunKRiAMFk", "XXFSPn4HtN4", ORIGINAL_TRACK, OTHER_THEME],
	["The Devil Incarnate", new Set([TITLE.VERSE]), { title: "VERSE" }, "NSsDzh0cvog", "jTXXW1GddKU", ORIGINAL_TRACK, OTHER_THEME],
	["Theatore Creatore", new Set([TITLE.VERSE]), { title: "VERSE" }, "hfIJUzNsn4g", "99-ylJ8NO0o", ORIGINAL_TRACK, OTHER_THEME],
	["激烈!!!!ファミレスガールは帰しま1000!!!!", new Set([TITLE.VERSE]), { title: "VERSE" }, "3urU5OzMCK8", "南ノ南 feat.9Lana", ORIGINAL_TRACK, OTHER_THEME],
	["〚隔絶〛 ～Flame of Determination", new Set([TITLE.VERSE]), { title: "VERSE" }, "j9uzmEmqrR4", "TERU FOX × Yukino feat. Iris", ORIGINAL_TRACK, OTHER_THEME],
	["〚献身〛 ～Paradox of Choice", new Set([TITLE.VERSE]), { title: "VERSE" }, "SnsJC0c7U5o", "Jehezukiel × KURORAK (feat. HideKy)", ORIGINAL_TRACK, OTHER_THEME],
	["〚盲従〛 ～Fantasia Sonata Flower", new Set([TITLE.VERSE]), { title: "VERSE" }, "Q1R-3C8jQzs", "P3-Studio", ORIGINAL_TRACK, OTHER_THEME],
	["〚空虚〛 ～Pyrophilia", new Set([TITLE.VERSE]), { title: "VERSE" }, "K3elMeCeXvI", "Black Box × Spyro Kong", ORIGINAL_TRACK, OTHER_THEME],
	["Aether Crest: Celestial", new Set([TITLE.VERSE]), { title: "VERSE" }, "W7f36vzxxiU", "void (Mournfinale) × 水野健治", ORIGINAL_TRACK, OTHER_THEME],
	["Crush the Dystopia", new Set([TITLE.VERSE]), { title: "VERSE" }, "HMQKReJY7Ds", "MintJam vs Masahiro \"Godspeed\" Aoki", ORIGINAL_TRACK, OTHER_THEME],
	["旅星に渇く", new Set([TITLE.VERSE]), { title: "VERSE" }, "iKMK6z6oZNs", "Yu-dachi", ORIGINAL_TRACK, OTHER_THEME],
	["ずんずんサファリ", new Set([TITLE.VERSE]), { title: "VERSE" }, "f6NKrsagth8", "ずんずんサファリ", ORIGINAL_TRACK, OTHER_THEME],
	["jaQup", new Set([TITLE.VERSE]), { title: "VERSE" }, "ptPRaIPHgRQ", "owl＊tree", ORIGINAL_TRACK, OTHER_THEME],
	["HeinousЯeaper", new Set([TITLE.VERSE]), { title: "VERSE" }, "6GmHzZkodd8", "seatrus", ORIGINAL_TRACK, OTHER_THEME],
	["MegiddØ", new Set([TITLE.VERSE]), { title: "VERSE" }, "KjSJ8FQo6rg", "BlackY VS 大国奏音", ORIGINAL_TRACK, OTHER_THEME],
	["Crossmythos Rhapsodia", new Set([TITLE.VERSE]), { title: "VERSE" }, "TkykXzvtFjc", "Acotto vs Potwi", ORIGINAL_TRACK, OTHER_THEME],
];
